### ISSUE TITLE
Consul to Kube 

### ISSUE THREAD

**Issue by philipcristiano** [Beldur/kube2consul#3]
Hi! Think looks like it solves the same situation I'm in as well! Is this a something you are continuing to run? 

I will also need to sync consul services to create Kube services with consul-derived endpoints in Kube. Is this something worth contributing back/something you have any interest in?

**Comment by philipcristiano** [comment]
notify @beldur (in case you don't get messaged for new issues).

**Comment by beldur** [comment]
Hi,

for the moment I don't have time to do any work on `kube2consul`. But I'm happy to accept pull request or give other people commit rights if they want to expand this little project in a meaningful and consistent way.

As I understand your feature request, it will mean to control kube services based on consul services. So more like a `consul2kube` 😄 I don't know if `kube2consul` would be the right spot to provide this functionality. Maybe another/new project would be better suited.

Please let me know what you think about it.

**Comment by philipcristiano** [comment]
Thanks for the reply! Yeah the naming would lead to this not being the completely right place. I'll likely start a new project to handle the `consul2kube` part of it. Depending on how that goes I may include similar logic from this into that project or make a PR to add filtering. Would at some point want to prevent consul services from being re-registered into consul (if this doesn't have a way to do that already).
